dbpf("$(PREFIX)ROI$(CHAN):EnableY", "Enable")
dbpf("$(PREFIX)ROI$(CHAN):MinY", "$(ADDR)")
dbpf("$(PREFIX)ROI$(CHAN):SizeY", 1)
dbpf("$(PREFIX)ROI$(CHAN):EnableCallbacks", "Enable")
dbpf("$(PREFIX)MCA$(CHAN):EnableCallbacks", "Enable")
dbpf("$(PREFIX)ROIStat$(CHAN):EnableCallbacks", "Enable")

dbpf("$(PREFIX)SCA$(CHAN):0:AttrName", "CHAN$(CHAN)SCA0")
dbpf("$(PREFIX)SCA$(CHAN):1:AttrName", "CHAN$(CHAN)SCA1")
dbpf("$(PREFIX)SCA$(CHAN):2:AttrName", "CHAN$(CHAN)SCA2")
dbpf("$(PREFIX)SCA$(CHAN):3:AttrName", "CHAN$(CHAN)SCA3")
dbpf("$(PREFIX)SCA$(CHAN):4:AttrName", "CHAN$(CHAN)SCA4")
dbpf("$(PREFIX)SCA$(CHAN):5:AttrName", "CHAN$(CHAN)SCA5")
dbpf("$(PREFIX)SCA$(CHAN):6:AttrName", "CHAN$(CHAN)SCA6")
dbpf("$(PREFIX)SCA$(CHAN):7:AttrName", "CHAN$(CHAN)SCA7")
dbpf("$(PREFIX)SCA$(CHAN):8:AttrName", "CHAN$(CHAN)DTFactor")
dbpf("$(PREFIX)SCA$(CHAN):9:AttrName", "CHAN$(CHAN)DTPercent")
dbpf("$(PREFIX)SCA$(CHAN):EnableCallbacks", "Enable")
dbpf("$(PREFIX)SCA$(CHAN):TS:EnableCallbacks", "Enable")

