TOP = ../..
include $(TOP)/configure/CONFIG
ARCH = linux-x86_64
TARGETS = envPaths
TARGETS += stexample.boot
TARGETS += xspress3-medm.sh
TARGETS += xspress3-edm.sh
include $(TOP)/configure/RULES.ioc
include $(TOP)/configure/RULES.iocDls
